# Generated by Django 4.0.5 on 2022-06-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pk', models.CharField(max_length=255, verbose_name='Номер')),
                ('text', models.CharField(max_length=255, verbose_name='Описание')),
                ('file', models.FileField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
